# Generated by Django 4.2.24 on 2025-09-16 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='role',
            field=models.CharField(default='CUSTOMER', max_length=20),
        ),
    ]
