# Generated by Django 4.2.24 on 2025-09-16 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_customer_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='role',
        ),
    ]
